### ISSUE TITLE
Review 'unconfirmed' calculation

### ISSUE THREAD

**Issue by baentsch** [daniel-karl/covid19-map#12]
![image](https://user-images.githubusercontent.com/57787676/77222396-fdeed700-6b52-11ea-8e6f-914b414321e2.png)

It also follows my understanding that 'unconfirmed' numbers should be "addons" to confirmed ones, i.e., I'd expect the above to state ">51.8K at avg. test rate"

**Comment by daniel-karl** [comment]
Italy is amongst the top testers, they are doing much better than average. Thus, scaling according to difference from world average shrinks the number. I thought about thresholding, but then thought it could be interesting to see "how much" better than average a country is doing.

**Comment by baentsch** [comment]
I'd still think
- one should display 'confirmed`+`unconfirmed` (if `test coverage` is active) as the figure interesting to viewers --I would argue-- is the "overall [probably] infected" rate
- use a similar colour for that (again, as it's conceptually the same and because more colours just confuse)
It's clear that Italy would only get a slightly bigger circle, while India for example 'explodes'

**Comment by daniel-karl** [comment]
We currently scale according to the global/local ratio: `projected = confirmed * (globalTest/localTestRate)`. Isn't this exactly the process you describe (besides color)?

(the variable should rather be called `projected` in the code, not `unconfirmed`....kinda misleading...sorry 😬)

**Comment by baentsch** [comment]
Hmm -- intuitively, I'm still not sure this makes sense to people: I'd change this view if either we'd add this projection _of infections_ to the confirmed _infections_ (my original proposal with the `1+...` logic or b) we'd show the projections standalone (disable at that moment the other views which are based on 'hard facts' -- this projection isn't: It's goal was to show (rough size of) a problem.

**Comment by daniel-karl** [comment]
Say country X perfectly matches global avg. testing rate.

Then Testing Rate Factor (TRF) `global/local` would be 1.

Then `(1 + TRF) * confirmed = 2 * confirmed` - while in fact it should be exactly `1 * confirmed`, since local testing matches global testing (i.e. nothing to project here).

**Comment by daniel-karl** [comment]
any further thoughts on this?
