### ISSUE TITLE
Polygon overlay with countries

### ISSUE THREAD

**Issue by daniel-karl** [daniel-karl/covid19-map#17]
@baentsch made a nice feature where aggregated values are shown in tooltips.

Unfortunately this got lost when transitioning from react simple maps to leaflet maps.

code is still in place but polygons need to be painted transparently on new map

**Comment by daniel-karl** [comment]
I think now we rather have the other problem: find a way to show unaggregated...close this?

**Comment by baentsch** [comment]
Agree
