### ISSUE TITLE
Remove confirmed, deceased and confirmed

### ISSUE THREAD

**Issue by ojsimon** [daniel-karl/covid19-map#20]
Hi, 

Is there an easy way to remove - Red (confirmed), Black (deceased) and Blue (confirmed) from the map. Leaving just the green (recovered) on the map?

I tried to do this by removing the variables for confirmed and deceased, but it gave some errors and I couldn't remove the coloured circles from the map itself. 

Any suggestions?

Thanks

**Comment by daniel-karl** [comment]
do you want me to take care of it, or should i give you some ideas on how you could implement it yourself (if you want to learn it)?

if you want to do it yourself:
1. add toggle buttons in the legend

**Comment by daniel-karl** [comment]
for example, right now where it says

`{ this.confirmedMarkers() }`

you could do

`{ false/true/someVariable && this.confirmedMarkers() }`

**Comment by baentsch** [comment]
Given Johns Hopkins doesn't report Recovered cases any more -- I'd think this issue is moot now, so let's close it.
