### ISSUE TITLE
Tooltip in Momentum mode

### ISSUE THREAD

**Issue by haehn** [daniel-karl/covid19-map#24]
Great work - somehow the tooltips do not work anymore after switching to 24h change mode.

**Comment by daniel-karl** [comment]
We currently hide the regular tooltip since in change mode the bubbles represent something different. We will have to come up with a special tooltip in this mode, that shows those values, and maybe also a graph the visualizes the momentum across the past days.

**Comment by daniel-karl** [comment]
added tooltip
