### ISSUE TITLE
Containment Score Leaderboard

### ISSUE THREAD

**Issue by rbishop360** [daniel-karl/covid19-map#28]
Hi, thank you for this great project. I have an idea for a new feature.

**Feature:** STAYING@HOME Leaderboard

**Description:** Rank countries, provinces and states by their STAYING@HOME score in a gamification system. The leaderboard shows where they stand in relation to their peers and highlights changes.

**Purpose:** Improve the world's response to _#FlattenTheCurve_ through a viral leaderboard system that promotes staying at home and saving lives.

**Possible sub-features:**
- Country rankings
- State and province rankings (within a single country; i.e. United States, Canada)
- Highlight changes in rankings when new data becomes available or on a fixed schedule
- Ability to share "my" country's, state's, or province's current rank on social media to encourage STAYING@HOME behaviour
- Will need some way to normalize the rankings when comparing countries. Perhaps rankings by defined cohorts so peer countries are grouped based on characteristics, such as their relative point in the virus' life-cycle.

This idea varies from the scope of the current map. However, after searching across many projects, I found that your STAYING@HOME score is unique and contributes to this idea.

**Comment by baentsch** [comment]
@rbishop360 Thanks for this suggestion. @daniel-karl and I had a conversation earlier today as to the 'gamification' aspect of the STAY@HOME score (and a discussion as to whether to call it that way as it's really a way to show the change rates per country), so the numbers are there and are shown when you hover over each country.... In other words, you'd suggest a page showing the current say "Top 10 countries" (states, etc)?

**Comment by rbishop360** [comment]
@baentsch Yes, I'd suggest a separate page. Perhaps a table that contains each country and their relative position. Ranked by top to worst performers. It would be useful for a user to have the ability to search for a specific country (i.e. their home country) so that they can quickly see how they are performing amongst their peers. I wouldn't limit it to just the top 10 because we want to encourage behaviour of those below the the cut-off. 

Some of these details could be exposed on the map's country hover. Perhaps just the current rank value i.e. "35th out of 238". And a link to the leaderboard.

**Comment by daniel-karl** [comment]
@rbishop360 thanks for your feedback. We have tons of space on the right side of the UI, where I was intending to build some graphs / leaderboards as you mentioned. 

With STAYING@HOME Score in particular we should do it in a way that the leaderboard only shows countries that are currently in the view. Otherwise you'd probably have dozens regions from China with the High-Score, before there's any real action in the leaderboard.

Step 1: It would be useful to refactor the Staying@Home computation into the part where all the data is loaded (there's a JSON object in confirmed/recovered/deaths/etc. for each region), to have the score available everywhere in the code. Right now it's only being computed in the tooltip.

**Comment by baentsch** [comment]
@daniel-karl agree with Step 1 -- what about creating at that moment also additional, 'aggregate' entries for those places where there's no country-wide stats (US, CN, CA, FR, AU) and then only show _those_ in the leaderboard (i.e., only compare countries and only compare states within a country)? This way, China would only be one entry -- and may even be moving out of view if there's indeed a way to scope this as per your suggestion... (and my old code for aggregation may be re-used :-)

**Comment by daniel-karl** [comment]
Good point! Technically, I woudn't keep this in mind when developing this feature (#28) too much. 
But then, fixing the newly opened #30 will automatically solve what you suggest, because this will then replace all the distributed entries by their aggregation in the map, and therefore also in the leaderboard.

**Comment by rbishop360** [comment]
> With STAYING@HOME Score in particular we should do it in a way that the leaderboard only shows countries that are currently in the view. Otherwise you'd probably have dozens regions from China with the High-Score, before there's any real action in the leaderboard.

Agreed. I had suggested this by placing countries into cohorts, so their rankings are true to their peers. I like your suggestion as well, as I suspect cohorts would just be a representation of neighbouring countries (which the map will handle).

How would this work for drilling within a country that has states or provinces? i.e. I want to see how only U.S. States rank. In terms of virality, this ranking would be something the American people would be checking daily. It should be easy to get to that information.

I'm excited to see your feedback on this and hope you are able to implement it. I can help to market the release of this feature, but sadly I'm limited in being able to make code contributions.

**Comment by daniel-karl** [comment]
We will respect this feedback when we get to implementing this. Thanks a lot, this will be really helpful to whoever will contribute this feature!

"Aggregation" is something we have on the radar, so hopefully we will find a good way to include this in the S@H leaderboard, too. Probably we will just have a checkbox to show the aggreate OR individual states in the leaderboard.

🚀 🚀 🚀

**Comment by daniel-karl** [comment]
#30

**Comment by rbishop360** [comment]
@daniel-karl 
![image](https://user-images.githubusercontent.com/6842242/77496520-86a29700-6e21-11ea-945f-49130d8c41f6.png)

Example of social demand for rankings.

**Comment by daniel-karl** [comment]
@rbishop360 
Unfortunately we don't have a data source that shows individual state (or even county) right now since Johns Hopkins does not report this level of detail any longer. I don't know why they are not doing this any more :/

**Comment by rbishop360** [comment]
@daniel-karl  That's terrible news. Looks like they added County (FIPS) to the Daily Reports, effective 3-22-2020. You could aggregate to state level by summing all counties in the State. Completely changes the data ingress process since you need to pull in daily files and do the aggregation. Sure makes it fun :)

**Comment by daniel-karl** [comment]
added leaderboard
