### ISSUE TITLE
Adjust Containment Score to take projected cases into account in projection mode

### ISSUE THREAD

**Issue by arunima-chaudhary** [daniel-karl/covid19-map#29]
Thanks for the wonderful viz!

It would be great if we could add testing into account for the STAYING@HOME score. This might further reflect the response levels and imminent threats for different countries.

**Comment by daniel-karl** [comment]
This could be done fairly easily by replacing "confirmed" with "projected" in the tooltip function. Before, one also needs to copy and project the momentum similar to the size projection as can be seen in the function that loads the confirmed data set.

**Comment by daniel-karl** [comment]
actually i realized we cannot do this right now because we don't have historic testing data
