### ISSUE TITLE
Time-log plots

### ISSUE THREAD

**Issue by baentsch** [daniel-karl/covid19-map#32]
Another idea that should be easy to add -- but I wonder whether to really do it (and how to visualise) as it has big "scare potential": We could compute ppm rates per day per country. With this we _could_ make statements like ("x days behind Italy"). If that number grows bigger, the "Stay@Home" score could go up. If it shrinks or even turns negative, boy is that country in trouble....

**Comment by daniel-karl** [comment]
this would like the time-corrected time-log plots - people have done this, and this is also what i had in mind in my comment from https://github.com/daniel-karl/covid19-map/issues/24

**Comment by daniel-karl** [comment]
see here:
http://nrg.cs.ucl.ac.uk/mjh/covid19/22mar2020/covid-eu.png

**Comment by daniel-karl** [comment]
we should have that plot somewhere and add the curve when someone selects or hovers a region

**Comment by daniel-karl** [comment]
do it horizontally at the bottom of our screen rather than vertically
and then for each marker that is clicked add a row like that in the bottom
and maybe have a few activated by default

https://zbraniecki.github.io/covid19-timeseries/
