### ISSUE TITLE
U.S. County support (FIPS Code)

### ISSUE THREAD

**Issue by rbishop360** [daniel-karl/covid19-map#35]
@baentsch @daniel-karl 

Johns Hopkins plans to [add FIPS code in the new US time series tables](https://github.com/CSSEGISandData/COVID-19/issues/1250) in the "following days".

This allows U.S. counties to be included in the project. As the U.S. begins to ramp up their battle, users would appreciate the ability to drill in so they can get detailed results on their local counties.

[FIPS code reference file from census.gov](https://www.census.gov/geographies/reference-files/2018/demo/popest/2018-fips.html)
[GeoJSON](https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json)

**Comment by LucidObscurity** [comment]
What's the price (in bottles of Purell) to get those files "back-filled" with this data (with historical numbers)? Thanks.

**Comment by rbishop360** [comment]
A suggestion on a possible way to implement. If you could select a state instead of hover, it could zoom the map and show the county overlay within the state. Then the user could interact with each county.

**Comment by daniel-karl** [comment]
Will be resolved through #40 and #41
