### ISSUE TITLE
Bug in JH v1/v2 toggle

### ISSUE THREAD

**Issue by baentsch** [daniel-karl/covid19-map#39]
Actually 2 bugs:
1) Nuisance (but still wrong): When selecting a date after the v1/v2 switch, old data gets displayed when selecting v1 -- wouldn't it be sensible to disable toggling to v1 when a date past 3/23 is selected?
2) Bad: When selecting a date prior to the switch (e.g., 3/22), the numbers displayed when just toggling between JHv1/v2 are *not the same*.

**Comment by daniel-karl** [comment]
1.) Agreed!
2.) This might be *because* of 1.) (what you see on 3/25 in v1 is in fact 3/23)...

**Comment by daniel-karl** [comment]
Fixed 2) which seems to fix 1), too. Please confirm.

**Comment by baentsch** [comment]
Nope. To reproduce, please select for example to 18.3.20 and toggle v1/v2: You will see differences -- and they're not as big as between 18.3.20 and 23.3.20 (JH cutover).

Side note: I don't particularly like the new location of the date bar. But that just as a side remark.
