### ISSUE TITLE
Add "tested" metric to leaderboard

### ISSUE THREAD

**Issue by rbishop360** [daniel-karl/covid19-map#50]
Show the number of tests in the leaderboard.

**Comment by rbishop360** [comment]
Also add it to the total metrics at the top right of the page.

Mock-up:
![image](https://user-images.githubusercontent.com/6842242/77855277-5d855c00-71bd-11ea-8e17-c556b7eb15c6.png)

**Comment by daniel-karl** [comment]
We don't have historic testing data available right now.

JH CSSE announced they would soon provide historic testing data, so I was going to hold off with this feature until that happened.

**Comment by JakaKokosar** [comment]
> JH CSSE announced they would soon provide historic testing data, so I was going to hold off with this feature until that happened.

Where was this published? Could you please link me the source? Thanks!

**Comment by daniel-karl** [comment]
added
