### ISSUE TITLE
Responsive leaderboard

### ISSUE THREAD

**Issue by rbishop360** [daniel-karl/covid19-map#51]
When viewing on a tablet, such as iPad, the leaderboard takes up over 50% of the screen. An idea is to make the leaderboard responsive depending on form factor. Perhaps only show rank, active cases, location, and containment score by default with ability to expand the leaderboard to see full metrics. 

Current view on iPad:
![image](https://user-images.githubusercontent.com/6842242/77855373-0c299c80-71be-11ea-80f4-042044a72f53.png)

**Comment by daniel-karl** [comment]
Interesting - it also appears the date control is cut off?!!?

**Comment by rbishop360** [comment]
Date control still appears.

iPad Portrait:
![image](https://user-images.githubusercontent.com/6842242/77859140-aba65980-71d5-11ea-99e1-c63e655d2212.png)


iPad Landscape:
![image](https://user-images.githubusercontent.com/6842242/77859148-b7921b80-71d5-11ea-93ba-6614254dd130.png)


iPad Pro Portrait:
![image](https://user-images.githubusercontent.com/6842242/77859187-e5776000-71d5-11ea-84f4-07986e9d59be.png)


iPad Pro Landscape:
![image](https://user-images.githubusercontent.com/6842242/77859182-dee8e880-71d5-11ea-9f40-7f0cfc45ecf3.png)

**Comment by daniel-karl** [comment]
i made the timeline control collapsible - hope this will help you to enjoy a better view. i don't have the capacity to do full UI optimization on all devices, but it doesn't look bad to me on your screen. closing this.
