### ISSUE TITLE
Expand logarithmic comparison graph

### ISSUE THREAD

**Issue by rbishop360** [daniel-karl/covid19-map#52]
The logarithmic comparison graph is small and hard to see. It would be nice if a user could expand it so you can more easily compare the data.

Current view:
![image](https://user-images.githubusercontent.com/6842242/77855525-fbc5f180-71be-11ea-87f6-0ea2d2f63ef2.png)

**Comment by rbishop360** [comment]
Would be nice to be able to produce something like this

![image](https://user-images.githubusercontent.com/6842242/77855708-219fc600-71c0-11ea-8f5e-d9f7056b98bf.png)

**Comment by daniel-karl** [comment]
Since this is a very isolated task I will declare this as a good first task to get to know the code base and count on some contributor from the community to contribute this one!

**Comment by daniel-karl** [comment]
added expand button
