### ISSUE TITLE
Blank react app github page

### ISSUE THREAD

**Issue by LukasSkarnulis** [daniel-karl/covid19-map#55]
So I have a common problem, I've uploaded my react app to github pages and I get a blank page and two errors: loading failed for the script with source. I've uploaded three react apps to github pages before, but this is a first error and I looked for solutions, but none of them fit. I've uploaded it with npm run deploy. I though that the local storage might get in a way, so I commented it out, but that still wasn't the case. Here's link to repository:

https://github.com/LukasSkarnulis/talech-task

**Comment by daniel-karl** [comment]
Sorry, how is this related to this COVID19 map? The source code in your repo doesn't appear to be a fork of this.
