### ISSUE TITLE
Show (change in) death rate somewhere

### ISSUE THREAD

**Issue by daniel-karl** [daniel-karl/covid19-map#56]

**Comment by abalib** [comment]
thanks taking my suggestion.  To recap calculate the death rate, the delta from yesterday or the delta of 3 day moving averages. Proposing to either plot it on the map or display it on the leaderboard.  Proposing to calculate the rate as a percentage, say death rate increased %10 or decreased (-20%).

**Comment by daniel-karl** [comment]
we are now showing the change in deaths in the momentum mode, where already the change in active cases has been shown.

we will show growth rates of all numbers directly in the leaderboard, so closing this special case.

**Comment by daniel-karl** [comment]
@abalib just to give you a follow up - just rolled out an improved version of the leaderboard: when in momentum mode it shows the change since the selected period rather than the cumulative number

**Comment by abalib** [comment]
> @abalib just to give you a follow up - just rolled out an improved version of the leaderboard: when in momentum mode it shows the change since the selected period rather than the cumulative number
@daniel-karl  I see no negative numbers in the momentum mode.  I tried all 3 momentum modes 24 hours, 3 and 7 days.  I see no decrease in deaths or confirmed cases anywhere in the world.  The smallest value I see is +0.   Is it a bug or is it because there is really no decrease (bleak) anywhere or I am doing something wrong?

**Comment by daniel-karl** [comment]
If you scroll all the way down there are some - but there's also a strange bug in terms of sorting in the negatives - I didn't find the time to investigate in depth yet what causes that...

**Comment by abalib** [comment]
Yes.  I finally did see one negative.  See the graphic which is sorted by the green column.  Sort problem might be not just negatives.  Look at where Iceland is.

![image](https://user-images.githubusercontent.com/14985008/78259477-c4ab5500-74ca-11ea-9af6-5a00c2c71283.png)

**Comment by abalib** [comment]
or this
![image](https://user-images.githubusercontent.com/14985008/78259873-3e434300-74cb-11ea-8d68-fc7e342cd4b8.png)
