### ISSUE TITLE
Sorting in leaderboard seems off sometimes

### ISSUE THREAD

**Issue by ItsMeAtHome** [daniel-karl/covid19-map#57]
Taking Luxembourg as an example (on 2April), they are listed as 238th with 46 deaths ppm, well above the many 0 ppm listed 130th (where the correct sorting seems to end).
I also noticed that in the map (once population is checked) Luxembourg does not get a glyph. (possibly related?)
Note, Luxembourg is just an example there are quite a few others in the list that  have the same.
(I can imagine that countries with less then 1m population can distort the picture, so maybe add a check box filter for this)

**Comment by daniel-karl** [comment]
Thanks!! We'll take a look at that!

**Comment by abalib** [comment]
FYI https://github.com/daniel-karl/covid19-map/issues/56#issuecomment-607873560

**Comment by daniel-karl** [comment]
Should be fixed now - we had a setting where countries < 1 M people were always sorted towards the end
