### ISSUE TITLE
US reporting broken

### ISSUE THREAD

**Issue by baentsch** [daniel-karl/covid19-map#60]
![image](https://user-images.githubusercontent.com/57787676/79204755-5442f300-7e3d-11ea-81a9-c53f73b1d83f.png)
US states are gone (intentionally, I guess -- but a loss) --but the picture (if visible) shows there's a large dead US population displayed in the Gulf of Guinea (?)

**Comment by daniel-karl** [comment]
Looks like they updated the US States file to include new information on testing.
