### ISSUE TITLE
Github Pages

### ISSUE THREAD

**Issue by ojsimon** [daniel-karl/covid19-map#8]
Hi,

when I clone repo and push to Github pages is shows a blank page [Here](https://ojsimon.github.io/covid19map/)

Any suggestions why this is?

Thanks

**Comment by daniel-karl** [comment]
No clue, but I can roll out your code if you make a Pull Request, so everybody can see your new feature(s)?
 
I would also add you to list of contributors, of course. Let's combine our efforts!
 
Cheers,
Daniel
 
----- Original message -----From: Oliver Simon <notifications@github.com>To: daniel-karl/covid19-map <covid19-map@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: [EXTERNAL] [daniel-karl/covid19-map] Github Pages (#8)Date: Fri, Mar 20, 2020 9:41 AM 
 
Hi,
when I clone repo and push to Github pages is shows a blank page Here
Any suggestions why this is?
Thanks

**Comment by daniel-karl** [comment]
Oh wait - you pushed to gh-pages branch via `npm run deploy`, right?

**Comment by daniel-karl** [comment]
@ojsimon Added instructions to README.md here
